# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
#  schedule:
#    - cron: '*/60 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Building
        run: |
          sudo apt install squashfs-tools
          git clone https://github.com/ThePoorPilot/Unofficial-Spotify.git
          cp ./Unofficial-Spotify/auto-build/token.txt ./
          mv ./Unofficial-Spotify/auto-build/auto.sh ./Unofficial-Spotify
          sed -i 's/insert_token_here/'"${{ secrets.SECRET_TOKEN }}"'/g' ./token.txt
          cd ./Unofficial-Spotify
          ./auto.sh
          mv ./auto.sh ./auto-build
          rm *.snap
          rm -r ./debpkgs
          rm -r ./snap_files
          rm ./*.deb
          git config --global user.name "ThePoorPilot"
          git config --global user.email "ios8jailbreakpangu@gmail.com"
          git add .
          git commit -m 'changed version number in auto.sh'
          git push https://ThePoorPilot:"${{ secrets.PASSWORD }}"@github.com/ThePoorPilot/Unofficial-Spotify.git
          cd ../
          rm ./token.txt
